### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by ghost** [Royalgamer06/steam-free-apps#1]
Can you please write how to use this?

**Comment by Revadike** [comment]
1. Download and Install [NodeJS](https://nodejs.org/en/)
2. Download [this repository](https://github.com/Royalgamer06/steam-free-packages/archive/master.zip)
3. Extract it anywhere and run install.bat (one-time only) to install the needed libraries
4. Edit config.json and include your information and preferences
5. Run run.bat any time after completing step 1-4
6. Minimize if you wish and it will periodically request free packages for your steam account

**Comment by ghost** [comment]
Thanks
