### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by SomeRandomGithubGuy** [Royalgamer06/steam-free-apps#10]
![capture](https://cloud.githubusercontent.com/assets/28699558/26045437/d80d01b2-3967-11e7-8a28-de42e16b0413.PNG)
The above error is caused whenever I try to run install.bat
I also get other various errors such as modules.js error.

Thanks.

**Comment by Revadike** [comment]
It's not an error. It's a warning. You can ignore it.

**Comment by SomeRandomGithubGuy** [comment]
However, when running the run.bat file, it produces similar error:
![capture 2](https://cloud.githubusercontent.com/assets/28699558/26055858/54030c08-3990-11e7-8908-1aa54107898d.PNG)

**Comment by Revadike** [comment]
you have to install module steamauth:
npm install steamauth

**Comment by SomeRandomGithubGuy** [comment]
I've installed every single module manually, still I have the same error. I've also tried to re-download and check it again yet the same results. I've downloaded both NodeJS 6.4 LTS and Latest v7
