### ISSUE TITLE
No new packages/apps being granted even though I still don't own over 2000 of them

### ISSUE THREAD

**Issue by YeAhxxx** [Royalgamer06/steam-free-apps#3]
I have tried waiting a few hours to see if it starts to work but It's all the same thing over and over again.
It used to work before but after a while it just started to stop.

```
Steam Guard App Code: XWRX6
[25-04-2017 12:33:30.397] Logged into Steam as [U:1:154739857]
[25-04-2017 12:33:30.523] Our account owns 1205 licenses
[25-04-2017 12:33:30.555] Our account has no limitations
[25-04-2017 12:33:30.557] Our account can invite friends
[25-04-2017 12:33:30.562] We have 0 VAC ban
[25-04-2017 12:33:32.974] Got web session
[25-04-2017 12:33:34.379] Cached app ownership
[25-04-2017 12:33:46.213] Found 2500 free apps of which 2059 are not owned by us yet
[25-04-2017 12:33:46.215] Attempting to request 50 subs (72571,72544,72447,72429,72411,72399,72380,72354,72328,72254,72228,72223,72204,72184,72154,72072,72039,72029,72010,71989,71984,71935,71924,71877,71851,71848,71784,71772,71761,71746,71600,71585,71575,71515,71500,71433,71425,71380,71347,71296,71287,71284,71225,71209,71196,71171,71168,71165,71043,71021)
[25-04-2017 12:33:46.588] No new packages were granted to our account
[25-04-2017 12:33:46.590] No new apps were granted to our account
[25-04-2017 12:33:46.591] Waiting 30 minutes for a new attempt
```

**Comment by ldeman** [comment]
i'm still on the prior version (RequestFreeApps.js), but i noticed after i got 3/4 of the way thru the list it's pretty much halted for me too @ "Found 1865 free apps of which 420 are not owned by us yet"

it'll probably work after another day or two though, there seems to be a limit beyond just the 50 at a time.  like after 24hour of requesting it needs a 24hour break or something like that.

**Comment by YeAhxxx** [comment]
I was on the prior version as well when this started to happen but even after using the latest one, it still continued to happen. Also note how I said "it just started to stop" because it all happened slowly until it stopped and now It's been over 2 days I haven't received any app/packages. Definitely not a 24 hour break thing.

**Comment by Revadike** [comment]
I think this is normal behavior. Some free-on-demand packages are always unsuccessful with requesting. You will end up with these left. I have "Found 2500 free apps of which 180 are not owned by us yet".
BTW, a change I made with the previous version: I first requesting free-to-play apps, now I am requesting free-on-demand packages instead. The reason why I did this, is that this is what the original free packages script also did and it includes more than just those free-to-play apps.

**Comment by YeAhxxx** [comment]
So I am not getting any new packages or apps from those remaining 2059 but its normal behavior ?
Maybe I will try increasing the 50 packages/apps limit to 2000 to see if it even adds a single one.

Edit: Okay so I did that and got 5 New packages and 11 New apps from out of 2000 requested. I think this is the limit of this program ? Nonetheless a cool program so thank you.

**Comment by Revadike** [comment]
I fixed the issue where it kept logging you in again and requesting the same packages.

**Comment by YeAhxxx** [comment]
You fixed that ? Im getting this exact thing always.

`[26-04-2017 02:04:55.029] No new packages were granted to our account
[26-04-2017 02:04:55.030] 14 New apps (70103,65524,55139,48900,21041,21040,21021,21020,20730,20720,20711,20701,20561,20560) were successfully granted to our account
[26-04-2017 02:04:55.035] Waiting 30 minutes for a new attempt
`

**Comment by Revadike** [comment]
Yeah. It's fixed for me. I set interval to 2 seconds and as you can see it requests new packages every time:
![](https://i.imgur.com/w1Z4KFr.png)

**Comment by YeAhxxx** [comment]
Weird. For me, im getting logged in each time and it requests the exact same 14 apps every time.
![capture](https://cloud.githubusercontent.com/assets/27961474/25425018/1fd1e308-2a88-11e7-9726-5c1d1bbad9f6.PNG)

**Comment by Revadike** [comment]
You shouldn't request all subs at once. Valve has a rate limit. That is the reason why I made this. If you have all subs requested, only then you will relog.p

**Comment by YeAhxxx** [comment]
Ah thats why. Yep its not relogging once I use less subs. Well anyway, Let's get back to the main issue which I was having from start. 

You said it should be like "Found 2500 free apps of which 180 are not owned by us yet" but for me its over 2000 and definitely not being reduced. So if this is normal then we can just close the issue.
![capture](https://cloud.githubusercontent.com/assets/27961474/25439431/0fab19a4-2aba-11e7-8944-e975e76302d4.PNG)

**Comment by Revadike** [comment]
Hmm. Even if you let it run? That's indeed a big number. What happens if you request apps instead of subs (like it used to do). You can use an older version for that: 
https://github.com/Royalgamer06/steam-free-packages/tree/e43e03f84498e1f210381e07a4203aaca65eba20

**Comment by YeAhxxx** [comment]
I doubt anything would change since I was using the older version when I posted this issue but I will give it a try and let you know.

Here's how it looks, I will let it run for a few hours
EDIT: Still the same lol 
![capture](https://cloud.githubusercontent.com/assets/27961474/25489604/ee19ed96-2b87-11e7-8507-2a39d936dae2.PNG)

**Comment by Revadike** [comment]
Maybe Valve's rate limit decreased. Or maybe they have max x subs/apps per y day(s)/week(s)/month(s). Who knows. I don't know what Valve's exact limits or flaws are, but the script does what it is designed to do. If you know how it can be improved, let me know.

**Comment by Revadike** [comment]
I just tried to request all free-on-demand packages on my secondary account, all at once: 
![](http://i.imgur.com/W4PFNM3.png)

**Comment by YeAhxxx** [comment]
Yeah, It could be valve's rate limit per month(s) or something. Anyway thank you for the script, It indeed worked flawless over the last couple weeks as it should so that the important thing. Maybe someone else comes up with the same issue as me because till now it's just me. Should I close the issue ?

**Comment by Revadike** [comment]
Nah, let's keep it open. It's good to discuss this. Or maybe reopen this issue with a more constructive informative first post.

**Comment by szymmirr** [comment]
Something's definitely wrong here. I let this script run for a couple hours yesterday and it barely added any packages (about 10 maybe, and you can see the package numbers repeat, as they were not added at all), so I doubt I have reached any limit. Moreover, none of them appeared there https://store.steampowered.com/account/licenses/ And the situation doesn't change today either.
![](https://cloud.githubusercontent.com/assets/12998256/25680191/47ced820-3050-11e7-9705-a973adf64c8a.png)

**Comment by Revadike** [comment]
Seems like SteamDB is limiting search results to 2500, which means it doesn't show any new subs. Probably the cause of this issue.

**Comment by Revadike** [comment]
I did some scraping on steamdb (ssh don't tell), and indeed there are way more free on demand packages than displayed. Around 4000 packages.

**Comment by jakey1995abc** [comment]
It says new apps are being added to my account but when I check https://store.steampowered.com/account/licenses/ there are no new entries. So then I try adding the exact same app IDs manually in the Steam console and they get added to the list... Has this app actually worked for anyone and added new things to anyone's account?

**Comment by r6d2** [comment]
> Has this app actually worked for anyone and added new things to anyone's account?

Never for me. I've followed every advice given here by other users to no avail. Nothing gets added to my account or licenses page.

**Comment by ldeman** [comment]
>Has this app actually worked for anyone and added new things to anyone's account?

never this version, only the old version for me.

**Comment by XVR1212** [comment]
doesn't work, any solutions/fix
![_wmokgpps2gdmnilmtjria](https://user-images.githubusercontent.com/30773996/29003837-de33e830-7ac6-11e7-9c0d-7a630447ecbd.png)

**Comment by hkkane** [comment]
same issue with XVR1212,hopefully Royalgamer06 update the code

**Comment by TsunaMoo** [comment]
Same here, it even keeps "adding" the same packages over and over. It never is truly added.

**Comment by Nazihh** [comment]
Just tried it (the new version, never tried the old one). Everything in .json is by default. 
But I just can't seem to get a new license.
![sin nombre](https://user-images.githubusercontent.com/31309605/29663785-333f1ebc-88cd-11e7-94ed-cd79d66ce207.png)
I waited more than 4 hours and still not getting any. Could anyone here help me?

**Comment by Revadike** [comment]
Use this instead guys: http://steam.madjoki.com/apps/free

**Comment by XVR1212** [comment]
@Royalgamer06 Thanks

**Comment by szymmirr** [comment]
ASF configuration seems to be kinda complicated, I assume I have to configure a bot (second steam account?) and send this command to him?

**Comment by Shartair** [comment]
@Royalgamer06 have you posted to cs.rin.ru yet? if not may i have the pleasure of sharing it?

**Comment by Revadike** [comment]
Go ahead
steamdb script is back too now.

**Comment by Shartair** [comment]
@Royalgamer06 ,which one? the one you use with the node.js?

**Comment by Revadike** [comment]
https://steamdb.info/freepackages/

**Comment by Revadike** [comment]
I updated the script. It will now listen to steam for new FoD packages and request those, while considering various limitations, like rate limit.

**Comment by JourneyOver** [comment]
Yet the new updated version doesn't even seem to work at all either.. I left it running all night long, and it never added any new packages at all to my account even though I have tons left.

this is the log here https://paste.ee/p/ktrvT
