### ISSUE TITLE
"TypeError: jsdom.jsdom is not a function"

### ISSUE THREAD

**Issue by jakey1995abc** [Royalgamer06/steam-free-apps#5]
Okay, I managed to get past the **"Error: Cannot find module 'steam-user'"** error by manually installing each package through cmd as admin (which installs it in the _C:\WINDOWS\System32\node_modules_ directory). But now that they are all installed I get this following error which I have no clue how to fix:

> C:\WINDOWS\system32\main.js:5
> $ = require("jquery")(jsdom.jsdom().defaultView),
>                             ^
> 
> TypeError: jsdom.jsdom is not a function
>     at Object.<anonymous> (C:\WINDOWS\system32\main.js:5:29)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:423:7)
>     at startup (bootstrap_node.js:147:9)
>     at bootstrap_node.js:538:3
> Press any key to continue. . .

**Comment by Revadike** [comment]
Yeah more users are complaining about this. I don't know. Try google?

**Comment by Tachyoin** [comment]
I found the solution:
With npm install jsdom you automatically install version 10.0.0 but you need version 9.12.0 to run the script.
https://github.com/tmpvar/jsdom/releases/tag/9.12.0

**Comment by jakey1995abc** [comment]
Thanks!
I edited install.bat to say

> @ECHO OFF
> npm install steamauth
> npm install steam-user
> npm install steamcommunity
> npm install jsdom@9.12.0
> npm install fs
> npm install request
> npm install cloudscraper
> npm install jquery
> pause

Now install works fine on every machine I have tested this on :)

@Royalgamer06 I'd recommend updating that file to contain this.

**Comment by Revadike** [comment]
Done 👍
