### ISSUE TITLE
Steam Guard

### ISSUE THREAD

**Issue by Jeckstart** [Royalgamer06/steam-free-apps#6]
Hi, thanks for script!
How can I use it with Steam Guard? I dont use Winauth

I get 'Javascript heap out of memory' error all the time

**Comment by ghost** [comment]
I think that if you use Steam Guard insted of Winauth you will need to enter SG code after you run the script, only thing that you need to enter before are in 'steam_credentials'

**Comment by Revadike** [comment]
Yeah, you will be asked to enter the code if you use steamguard.
