### ISSUE TITLE
linux support?

### ISSUE THREAD

**Issue by ghost** [Royalgamer06/steam-free-apps#7]
does this work on linux?

**Comment by ldeman** [comment]
yes

install node = https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04

then run the following commands to install the required packages for it to function
```
npm install fs
npm install request
npm install cloudscraper
npm install jsdom@9.12.0
npm install jquery
npm install node-steam
npm install steamauth
npm install steam-user
npm install steamcommunity
```

then launch the bot with the following command
```
nodejs --max_old_space_size=8096 main.js
```
