### ISSUE TITLE
HTTP error 503

### ISSUE THREAD

**Issue by iFEARR** [Royalgamer06/steam-free-apps#8]
![image](https://cloud.githubusercontent.com/assets/6118215/25780937/f276cb16-3339-11e7-91e9-1564f28983d7.png)

**Comment by ldeman** [comment]
did you edit the config.json to match your info?

**Comment by iFEARR** [comment]
I added my steam account. I didn't touch winauth

**Comment by iFEARR** [comment]
What I need to add in winauth part ?

**Comment by ldeman** [comment]
if you use steamguard instead of winauth then just make the flag stays "false" and ignore the rest of that portion of the config.  i'm not sure what info goes there if you do use winauth instead of steamguard though.

but it looks to me like there was no steam guard login & it is trying winauth instead and that's why it's throwing an error.

**Comment by iFEARR** [comment]
It asked me to put the steam guard code and I did. Also I have winauth_usage set to false.

**Comment by ldeman** [comment]
oh okay, sorry.  i thought the steamguard line was one line below "Logged into steam as..." but it's one line above it instead.   my bad.  =)

royalgamer06 will prob have to help you himself on this one.. sorry.

**Comment by iFEARR** [comment]
I don't know much node, but I looked at the main.js. after got web session, the script is trying to access steamdb.info
console.log("Got web session");
        var community = new SteamCommunity();
        community.setCookies(cookies);
        community.httpRequestGet("https://steamdb.info/login/", { ...

When I tried to browse steamdb from chrome, said steamdb is verifying your browser or something like that (like cloudflare). Maybe this is the problem ?

**Comment by ldeman** [comment]
that makes sense, i'd guess that's what's causing the issue too.   maybe royal can work around that verify/redirect somehow. 

edit:
it might actually require you to just be logged in steamdb.info too though, i'm not honestly sure.. i came from a prior version of this script that did things differently and required the login cookie manually entered into the config of the old script.  -- maybe worth a shot to try just logging in at least.

**Comment by iFEARR** [comment]
Doesn't work

**Comment by ldeman** [comment]
oops.. i'm getting the same thing too..

i thought i was testing the same version as you when i read about the error, but no.  i was still using the old one when testing (which still works), but after testing the same version you are on i get the same error.

**Comment by iFEARR** [comment]
Can I get this old version somewhere ?

**Comment by ldeman** [comment]
i'm not entirely sure what all was changed besides the need for sgtools.info cookie to be manually added to the config but...
https://github.com/Royalgamer06/steam-free-packages/tree/e43e03f84498e1f210381e07a4203aaca65eba20

**Comment by Revadike** [comment]
I don't know why it stopped working. SteamDB must have changed or blocked something. Seems the cookie method still works though.

**Comment by Rahzadan** [comment]
Cookie method also still works for me. Any way this can be updated to use newest features/fixes, but go back to using a cookie? I have no knowledge of how to make these things otherwise I'd do it myself.

**Comment by Revadike** [comment]
https://steamdb.info/forum/1386/free-packages/#reply-4152

**Comment by ldeman** [comment]
in short it looks to me like they don't care if you change it to use the cookie method, and it was probably cloudfare that eventually caught the node and prevented requests.

**Comment by Revadike** [comment]
Check out new update. It should be fixed now.
